# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dglm_scale_chunk <- function(ptr, idx, w, W0t, R0t, K, rho, Q, pptr, pidx, pw, n0, return_state = 0L) {
    .Call(`_spCF_dglm_scale_chunk`, ptr, idx, w, W0t, R0t, K, rho, Q, pptr, pidx, pw, n0, return_state)
}

dglm_gpoe_rows <- function(ptr, idx, w, tcol, m, P, Pv, P0v, vmx) {
    .Call(`_spCF_dglm_gpoe_rows`, ptr, idx, w, tcol, m, P, Pv, P0v, vmx)
}

lwr_chunk_cpp <- function(nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old) {
    invisible(.Call(`_spCF_lwr_chunk_cpp`, nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old))
}

lwr_chunk_glm_cpp <- function(nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, w_obs, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old) {
    invisible(.Call(`_spCF_lwr_chunk_glm_cpp`, nb_id, nb_dist, nb_id0_sexp, nb_dist0_sexp, sel_chunk, id_train_flag, resid, w_obs, x, x0_sexp, B_var, vc_cols, band, kernel_id, b_all, bv_inv_all, pv_inv_all, b_all0_sexp, bv_inv_all0_sexp, pv_inv_all0_sexp, b_old))
}

lwr_glm_fused_cpp <- function(coords, coords_cent, resid, w_obs, x, id_train, B_var, vc_cols, band, kernel_id, threshold, is_lm, coords0_sexp, x0_sexp, return_state = 0L) {
    .Call(`_spCF_lwr_glm_fused_cpp`, coords, coords_cent, resid, w_obs, x, id_train, B_var, vc_cols, band, kernel_id, threshold, is_lm, coords0_sexp, x0_sexp, return_state)
}

lwr_scatter0_cpp <- function(coords_cent, iw, b, ibv, sig, vc_cols, coords0, x0, band, kernel_id, threshold) {
    .Call(`_spCF_lwr_scatter0_cpp`, coords_cent, iw, b, ibv, sig, vc_cols, coords0, x0, band, kernel_id, threshold)
}

lwr_ds_chunk_cpp <- function(nb_id, nb_dist, sel_chunk, local_bands, kernel_id, vc, resid_area, X_area, W_area, a, agg_id, id_train_flag, x, B_var_col, c_shrink, b_all, bv_inv_all, pv_inv_all, b_old) {
    invisible(.Call(`_spCF_lwr_ds_chunk_cpp`, nb_id, nb_dist, sel_chunk, local_bands, kernel_id, vc, resid_area, X_area, W_area, a, agg_id, id_train_flag, x, B_var_col, c_shrink, b_all, bv_inv_all, pv_inv_all, b_old))
}

